// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    /// 返回码,200表示成功,其他表示失败
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 请求id，和request中的request_id对应
    #[prost(string, tag = "2")]
    pub request_id: ::prost::alloc::string::String,
    /// 返回信息
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(
        oneof = "response::ResponseType",
        tags = "4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14"
    )]
    pub response_type: ::core::option::Option<response::ResponseType>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ResponseType {
        #[prost(message, tag = "4")]
        AuthResponse(super::super::auth::AuthResponse),
        #[prost(message, tag = "5")]
        CardQueryResponse(super::super::query::CardQueryResponse),
        #[prost(message, tag = "6")]
        CardCountResponse(super::super::query::CardCountResponse),
        #[prost(message, tag = "7")]
        QueryIdsResponse(super::super::query::QueryIdsResponse),
        #[prost(message, tag = "8")]
        LinkQueryResponse(super::super::linkquery::LinkQueryResponse),
        #[prost(message, tag = "9")]
        BatchCardCommonResponse(super::super::write::BatchCardCommonResponse),
        #[prost(message, tag = "10")]
        BatchLinkCommonResponse(super::super::write::BatchLinkCommonResponse),
        #[prost(message, tag = "11")]
        UpdateLogLevelResponse(super::super::admin::UpdateLogLevelResponse),
        #[prost(message, tag = "12")]
        CardCountByGroupResponse(super::super::query::CardCountByGroupResponse),
        #[prost(message, tag = "13")]
        DatabaseStatsResponse(super::super::admin::DatabaseStatsResponse),
        #[prost(message, tag = "14")]
        QueryCardTitlesResponse(super::super::query::QueryCardTitlesResponse),
    }
}
