// This file is @generated by prost-build.
/// 字段值接口
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldValue {
    #[prost(string, tag = "1")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(oneof = "field_value::FieldType", tags = "2, 3, 4, 5, 6, 7, 8")]
    pub field_type: ::core::option::Option<field_value::FieldType>,
}
/// Nested message and enum types in `FieldValue`.
pub mod field_value {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum FieldType {
        #[prost(message, tag = "2")]
        TextField(super::TextFieldValue),
        #[prost(message, tag = "3")]
        NumberField(super::NumberFieldValue),
        #[prost(message, tag = "4")]
        DateField(super::DateFieldValue),
        #[prost(message, tag = "5")]
        EnumField(super::EnumFieldValue),
        #[prost(message, tag = "6")]
        WebLinkField(super::WebLinkFieldValue),
        #[prost(message, tag = "7")]
        AttachmentField(super::AttachmentFieldValue),
        #[prost(message, tag = "8")]
        DeriveField(super::DeriveFieldValue),
    }
}
/// 关联关系上的属性：衍生属性
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldValueOnLink {
    #[prost(string, tag = "1")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(oneof = "field_value_on_link::FieldType", tags = "2, 3, 4")]
    pub field_type: ::core::option::Option<field_value_on_link::FieldType>,
}
/// Nested message and enum types in `FieldValueOnLink`.
pub mod field_value_on_link {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum FieldType {
        #[prost(message, tag = "2")]
        NumberField(super::NumberFieldValue),
        #[prost(message, tag = "3")]
        DateField(super::DateFieldValue),
        #[prost(message, tag = "4")]
        EnumField(super::EnumFieldValue),
    }
}
/// 文本字段值
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextFieldValue {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub max_string_length: i64,
}
/// 数字字段值
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberFieldValue {
    #[prost(double, tag = "1")]
    pub value: f64,
}
/// 日期字段值
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateFieldValue {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
/// 枚举字段值（存储选项 ID 列表）
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumFieldValue {
    #[prost(string, repeated, tag = "1")]
    pub value: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 链接字段值
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkFieldValue {
    #[prost(string, tag = "1")]
    pub href: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
/// 附件字段值
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttachmentFieldValue {
    #[prost(message, repeated, tag = "1")]
    pub value: ::prost::alloc::vec::Vec<AttachmentItem>,
}
/// 附件项
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttachmentItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub uploader: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub created_at: i64,
    #[prost(int64, tag = "5")]
    pub size: i64,
}
/// 关联衍生字段值，存在于关联关系上
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeriveFieldValue {
    /// 对端卡片ID，使用u64类型
    #[prost(uint64, tag = "1")]
    pub opponent_card_id: u64,
    #[prost(oneof = "derive_field_value::FieldType", tags = "2, 3, 4")]
    pub field_type: ::core::option::Option<derive_field_value::FieldType>,
}
/// Nested message and enum types in `DeriveFieldValue`.
pub mod derive_field_value {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum FieldType {
        #[prost(message, tag = "2")]
        DateField(super::DateFieldValue),
        #[prost(message, tag = "3")]
        NumberField(super::NumberFieldValue),
        #[prost(message, tag = "4")]
        EnumField(super::EnumFieldValue),
    }
}
