// This file is @generated by prost-build.
/// 过滤条件容器
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Condition {
    #[prost(message, optional, tag = "1")]
    pub root: ::core::option::Option<ConditionNode>,
}
/// 条件节点（支持递归嵌套）
/// 可以是组合节点（ConditionGroup）或具体条件项
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionNode {
    #[prost(
        oneof = "condition_node::NodeType",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13"
    )]
    pub node_type: ::core::option::Option<condition_node::NodeType>,
}
/// Nested message and enum types in `ConditionNode`.
pub mod condition_node {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum NodeType {
        /// 组合节点（支持递归）
        #[prost(message, tag = "1")]
        Group(super::ConditionGroup),
        /// 标题条件
        #[prost(message, tag = "2")]
        Title(super::TitleConditionItem),
        /// 编号条件
        #[prost(message, tag = "3")]
        Code(super::CodeConditionItem),
        /// 文本条件
        #[prost(message, tag = "4")]
        Text(super::TextConditionItem),
        /// 数字条件
        #[prost(message, tag = "5")]
        Number(super::NumberConditionItem),
        /// 日期条件
        #[prost(message, tag = "6")]
        Date(super::DateConditionItem),
        /// 枚举条件
        #[prost(message, tag = "7")]
        EnumItem(super::EnumConditionItem),
        /// 价值流状态条件
        #[prost(message, tag = "8")]
        Status(super::StatusConditionItem),
        /// 卡片生命周期状态条件
        #[prost(message, tag = "9")]
        State(super::StateConditionItem),
        /// 关联卡片条件
        #[prost(message, tag = "10")]
        Link(super::LinkConditionItem),
        /// 链接属性条件
        #[prost(message, tag = "11")]
        WebLink(super::WebLinkConditionItem),
        /// 关键词条件
        #[prost(message, tag = "12")]
        Keyword(super::KeywordConditionItem),
        /// 卡片类型条件
        #[prost(message, tag = "13")]
        CardType(super::CardTypeConditionItem),
    }
}
/// 条件组（支持 AND/OR 逻辑）
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionGroup {
    #[prost(enumeration = "LogicOperator", tag = "1")]
    pub operator: i32,
    #[prost(message, repeated, tag = "2")]
    pub children: ::prost::alloc::vec::Vec<ConditionNode>,
}
/// ==============================================================================
/// 标题条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TitleConditionItem {
    #[prost(message, optional, tag = "1")]
    pub operator: ::core::option::Option<TitleOperator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TitleOperator {
    #[prost(oneof = "title_operator::OperatorType", tags = "1, 2, 3")]
    pub operator_type: ::core::option::Option<title_operator::OperatorType>,
}
/// Nested message and enum types in `TitleOperator`.
pub mod title_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Contains(super::TitleContainsOperator),
        #[prost(message, tag = "2")]
        Equal(super::TitleEqualOperator),
        #[prost(message, tag = "3")]
        In(super::TitleInOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TitleContainsOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TitleEqualOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TitleInOperator {
    #[prost(string, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// ==============================================================================
/// 编号条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CodeConditionItem {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// ==============================================================================
/// 文本条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
    #[prost(string, tag = "2")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<TextSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<TextOperator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextOperator {
    #[prost(oneof = "text_operator::OperatorType", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub operator_type: ::core::option::Option<text_operator::OperatorType>,
}
/// Nested message and enum types in `TextOperator`.
pub mod text_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::TextEqualOperator),
        #[prost(message, tag = "2")]
        NotEqual(super::TextNotEqualOperator),
        #[prost(message, tag = "3")]
        Contains(super::TextContainsOperator),
        #[prost(message, tag = "4")]
        NotContains(super::TextNotContainsOperator),
        #[prost(message, tag = "5")]
        StartsWith(super::TextStartsWithOperator),
        #[prost(message, tag = "6")]
        EndsWith(super::TextEndsWithOperator),
        #[prost(message, tag = "7")]
        IsBlank(super::TextIsBlankOperator),
        #[prost(message, tag = "8")]
        IsNotBlank(super::TextIsNotBlankOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextEqualOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextNotEqualOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextContainsOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextNotContainsOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextStartsWithOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextEndsWithOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextIsBlankOperator {}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TextIsNotBlankOperator {}
/// ==============================================================================
/// 价值流状态条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<StatusSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<StatusOperator>,
    /// 状态的顺序，用来支持 已超过、未到达这种操作符的过滤
    #[prost(string, repeated, tag = "3")]
    pub status_orders: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusOperator {
    #[prost(oneof = "status_operator::OperatorType", tags = "1, 2, 3, 4")]
    pub operator_type: ::core::option::Option<status_operator::OperatorType>,
}
/// Nested message and enum types in `StatusOperator`.
pub mod status_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::StatusEqualOperator),
        #[prost(message, tag = "2")]
        NotEqual(super::StatusNotEqualOperator),
        #[prost(message, tag = "3")]
        In(super::StatusInOperator),
        #[prost(message, tag = "4")]
        NotIn(super::StatusNotInOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusEqualOperator {
    #[prost(string, tag = "1")]
    pub stream_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusNotEqualOperator {
    #[prost(string, tag = "1")]
    pub stream_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusInOperator {
    #[prost(string, tag = "1")]
    pub stream_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusNotInOperator {
    #[prost(string, tag = "1")]
    pub stream_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// ==============================================================================
/// 卡片生命周期状态条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<StateSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<StateOperator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateOperator {
    #[prost(oneof = "state_operator::OperatorType", tags = "1, 2, 3, 4")]
    pub operator_type: ::core::option::Option<state_operator::OperatorType>,
}
/// Nested message and enum types in `StateOperator`.
pub mod state_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::StateEqualOperator),
        #[prost(message, tag = "2")]
        NotEqual(super::StateNotEqualOperator),
        #[prost(message, tag = "3")]
        In(super::StateInOperator),
        #[prost(message, tag = "4")]
        NotIn(super::StateNotInOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateEqualOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateNotEqualOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateInOperator {
    #[prost(string, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateNotInOperator {
    #[prost(string, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// ==============================================================================
/// 卡片类型条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardTypeSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardTypeConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<CardTypeSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<CardTypeOperator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardTypeOperator {
    #[prost(oneof = "card_type_operator::OperatorType", tags = "1, 2")]
    pub operator_type: ::core::option::Option<card_type_operator::OperatorType>,
}
/// Nested message and enum types in `CardTypeOperator`.
pub mod card_type_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::CardTypeEqualOperator),
        #[prost(message, tag = "2")]
        In(super::CardTypeInOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardTypeEqualOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardTypeInOperator {
    #[prost(string, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// ==============================================================================
/// 数字条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
    #[prost(string, tag = "2")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<NumberSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<NumberOperator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberOperator {
    #[prost(
        oneof = "number_operator::OperatorType",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10"
    )]
    pub operator_type: ::core::option::Option<number_operator::OperatorType>,
}
/// Nested message and enum types in `NumberOperator`.
pub mod number_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::NumberEqualOperator),
        #[prost(message, tag = "2")]
        NotEqual(super::NumberNotEqualOperator),
        #[prost(message, tag = "3")]
        GreaterThan(super::NumberGreaterThanOperator),
        #[prost(message, tag = "4")]
        LessThan(super::NumberLessThanOperator),
        #[prost(message, tag = "5")]
        GreaterThanOrEqual(super::NumberGreaterThanOrEqualOperator),
        #[prost(message, tag = "6")]
        LessThanOrEqual(super::NumberLessThanOrEqualOperator),
        #[prost(message, tag = "7")]
        Between(super::NumberBetweenOperator),
        #[prost(message, tag = "8")]
        NotBetween(super::NumberNotBetweenOperator),
        #[prost(message, tag = "9")]
        IsNull(super::NumberIsNullOperator),
        #[prost(message, tag = "10")]
        IsNotNull(super::NumberIsNotNullOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberEqualOperator {
    #[prost(double, tag = "1")]
    pub value: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberNotEqualOperator {
    #[prost(double, tag = "1")]
    pub value: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberGreaterThanOperator {
    #[prost(double, tag = "1")]
    pub value: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberLessThanOperator {
    #[prost(double, tag = "1")]
    pub value: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberGreaterThanOrEqualOperator {
    #[prost(double, tag = "1")]
    pub value: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberLessThanOrEqualOperator {
    #[prost(double, tag = "1")]
    pub value: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberBetweenOperator {
    #[prost(double, tag = "1")]
    pub min_value: f64,
    #[prost(double, tag = "2")]
    pub max_value: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberNotBetweenOperator {
    #[prost(double, tag = "1")]
    pub min_value: f64,
    #[prost(double, tag = "2")]
    pub max_value: f64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberIsNullOperator {}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberIsNotNullOperator {}
/// ==============================================================================
/// 日期条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
    #[prost(string, tag = "2")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<DateSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<DateOperator>,
    /// 时间精度: DAY, MILLISECOND
    #[prost(string, tag = "3")]
    pub time_precision: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateOperator {
    #[prost(
        oneof = "date_operator::OperatorType",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10"
    )]
    pub operator_type: ::core::option::Option<date_operator::OperatorType>,
}
/// Nested message and enum types in `DateOperator`.
pub mod date_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::DateEqualOperator),
        #[prost(message, tag = "2")]
        NotEqual(super::DateNotEqualOperator),
        #[prost(message, tag = "3")]
        Before(super::DateBeforeOperator),
        #[prost(message, tag = "4")]
        After(super::DateAfterOperator),
        #[prost(message, tag = "5")]
        BeforeOrEqual(super::DateBeforeOrEqualOperator),
        #[prost(message, tag = "6")]
        AfterOrEqual(super::DateAfterOrEqualOperator),
        #[prost(message, tag = "7")]
        Between(super::DateBetweenOperator),
        #[prost(message, tag = "8")]
        NotBetween(super::DateNotBetweenOperator),
        #[prost(message, tag = "9")]
        IsNull(super::DateIsNullOperator),
        #[prost(message, tag = "10")]
        IsNotNull(super::DateIsNotNullOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateEqualOperator {
    #[prost(oneof = "date_equal_operator::ValueType", tags = "1, 2")]
    pub value_type: ::core::option::Option<date_equal_operator::ValueType>,
}
/// Nested message and enum types in `DateEqualOperator`.
pub mod date_equal_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        #[prost(int64, tag = "1")]
        StaticValue(i64),
        #[prost(message, tag = "2")]
        ReferDate(super::ReferDate),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateNotEqualOperator {
    #[prost(oneof = "date_not_equal_operator::ValueType", tags = "1, 2")]
    pub value_type: ::core::option::Option<date_not_equal_operator::ValueType>,
}
/// Nested message and enum types in `DateNotEqualOperator`.
pub mod date_not_equal_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        #[prost(int64, tag = "1")]
        StaticValue(i64),
        #[prost(message, tag = "2")]
        ReferDate(super::ReferDate),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateBeforeOperator {
    #[prost(oneof = "date_before_operator::ValueType", tags = "1, 2")]
    pub value_type: ::core::option::Option<date_before_operator::ValueType>,
}
/// Nested message and enum types in `DateBeforeOperator`.
pub mod date_before_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        #[prost(int64, tag = "1")]
        StaticValue(i64),
        #[prost(message, tag = "2")]
        ReferDate(super::ReferDate),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateAfterOperator {
    #[prost(oneof = "date_after_operator::ValueType", tags = "1, 2")]
    pub value_type: ::core::option::Option<date_after_operator::ValueType>,
}
/// Nested message and enum types in `DateAfterOperator`.
pub mod date_after_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        #[prost(int64, tag = "1")]
        StaticValue(i64),
        #[prost(message, tag = "2")]
        ReferDate(super::ReferDate),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateBeforeOrEqualOperator {
    #[prost(oneof = "date_before_or_equal_operator::ValueType", tags = "1, 2")]
    pub value_type: ::core::option::Option<date_before_or_equal_operator::ValueType>,
}
/// Nested message and enum types in `DateBeforeOrEqualOperator`.
pub mod date_before_or_equal_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        #[prost(int64, tag = "1")]
        StaticValue(i64),
        #[prost(message, tag = "2")]
        ReferDate(super::ReferDate),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateAfterOrEqualOperator {
    #[prost(oneof = "date_after_or_equal_operator::ValueType", tags = "1, 2")]
    pub value_type: ::core::option::Option<date_after_or_equal_operator::ValueType>,
}
/// Nested message and enum types in `DateAfterOrEqualOperator`.
pub mod date_after_or_equal_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        #[prost(int64, tag = "1")]
        StaticValue(i64),
        #[prost(message, tag = "2")]
        ReferDate(super::ReferDate),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateBetweenOperator {
    #[prost(int64, tag = "1")]
    pub static_start_value: i64,
    #[prost(int64, tag = "2")]
    pub static_end_value: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateNotBetweenOperator {
    #[prost(int64, tag = "1")]
    pub static_start_value: i64,
    #[prost(int64, tag = "2")]
    pub static_end_value: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateIsNullOperator {}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DateIsNotNullOperator {}
/// 日期引用值
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReferDate {
    #[prost(string, tag = "5")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(oneof = "refer_date::ReferOnType", tags = "1, 2, 3, 4")]
    pub refer_on_type: ::core::option::Option<refer_date::ReferOnType>,
}
/// Nested message and enum types in `ReferDate`.
pub mod refer_date {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ReferOnType {
        #[prost(message, tag = "1")]
        ReferOnCurrentCard(super::ReferOnCurrentCard),
        #[prost(message, tag = "2")]
        ReferOnParameterCard(super::ReferOnParameterCard),
        #[prost(message, tag = "3")]
        ReferOnMember(super::ReferOnMember),
        #[prost(message, tag = "4")]
        ReferOnContextualCard(super::ReferOnContextualCard),
    }
}
/// ==============================================================================
/// 枚举条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
    #[prost(string, tag = "2")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<EnumSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<EnumOperator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumOperator {
    #[prost(oneof = "enum_operator::OperatorType", tags = "1, 2, 3, 4, 5, 6")]
    pub operator_type: ::core::option::Option<enum_operator::OperatorType>,
}
/// Nested message and enum types in `EnumOperator`.
pub mod enum_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::EnumEqualOperator),
        #[prost(message, tag = "2")]
        NotEqual(super::EnumNotEqualOperator),
        #[prost(message, tag = "3")]
        In(super::EnumInOperator),
        #[prost(message, tag = "4")]
        NotIn(super::EnumNotInOperator),
        #[prost(message, tag = "5")]
        IsNull(super::EnumIsNullOperator),
        #[prost(message, tag = "6")]
        IsNotNull(super::EnumIsNotNullOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumEqualOperator {
    #[prost(oneof = "enum_equal_operator::ValueType", tags = "1, 2")]
    pub value_type: ::core::option::Option<enum_equal_operator::ValueType>,
}
/// Nested message and enum types in `EnumEqualOperator`.
pub mod enum_equal_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        #[prost(message, tag = "1")]
        StaticValues(super::EnumStaticValues),
        #[prost(message, tag = "2")]
        ReferEnum(super::ReferEnum),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumNotEqualOperator {
    #[prost(oneof = "enum_not_equal_operator::ValueType", tags = "1, 2")]
    pub value_type: ::core::option::Option<enum_not_equal_operator::ValueType>,
}
/// Nested message and enum types in `EnumNotEqualOperator`.
pub mod enum_not_equal_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValueType {
        #[prost(message, tag = "1")]
        StaticValues(super::EnumStaticValues),
        #[prost(message, tag = "2")]
        ReferEnum(super::ReferEnum),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumInOperator {
    #[prost(oneof = "enum_in_operator::ValuesType", tags = "1, 2")]
    pub values_type: ::core::option::Option<enum_in_operator::ValuesType>,
}
/// Nested message and enum types in `EnumInOperator`.
pub mod enum_in_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValuesType {
        #[prost(message, tag = "1")]
        StaticValues(super::EnumStaticValues),
        #[prost(message, tag = "2")]
        ReferEnum(super::ReferEnum),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumStaticValues {
    #[prost(string, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumNotInOperator {
    #[prost(oneof = "enum_not_in_operator::ValuesType", tags = "1, 2")]
    pub values_type: ::core::option::Option<enum_not_in_operator::ValuesType>,
}
/// Nested message and enum types in `EnumNotInOperator`.
pub mod enum_not_in_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ValuesType {
        #[prost(message, tag = "1")]
        StaticValues(super::EnumStaticValues),
        #[prost(message, tag = "2")]
        ReferEnum(super::ReferEnum),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReferEnum {
    #[prost(string, tag = "5")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(oneof = "refer_enum::ReferOnType", tags = "1, 2, 3, 4")]
    pub refer_on_type: ::core::option::Option<refer_enum::ReferOnType>,
}
/// Nested message and enum types in `ReferEnum`.
pub mod refer_enum {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ReferOnType {
        #[prost(message, tag = "1")]
        ReferOnCurrentCard(super::ReferOnCurrentCard),
        #[prost(message, tag = "2")]
        ReferOnParameterCard(super::ReferOnParameterCard),
        #[prost(message, tag = "3")]
        ReferOnMember(super::ReferOnMember),
        #[prost(message, tag = "4")]
        ReferOnContextualCard(super::ReferOnContextualCard),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumIsNullOperator {}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnumIsNotNullOperator {}
/// ==============================================================================
/// 关联卡片条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<LinkSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<LinkOperator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkOperator {
    #[prost(oneof = "link_operator::OperatorType", tags = "1, 2, 3, 4, 5, 6")]
    pub operator_type: ::core::option::Option<link_operator::OperatorType>,
}
/// Nested message and enum types in `LinkOperator`.
pub mod link_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::LinkEqualOperator),
        #[prost(message, tag = "2")]
        NotEqual(super::LinkNotEqualOperator),
        #[prost(message, tag = "3")]
        In(super::LinkInOperator),
        #[prost(message, tag = "4")]
        NotIn(super::LinkNotInOperator),
        #[prost(message, tag = "5")]
        IsNull(super::LinkIsNullOperator),
        #[prost(message, tag = "6")]
        IsNotNull(super::LinkIsNotNullOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkEqualOperator {
    #[prost(oneof = "link_equal_operator::Value", tags = "1, 2")]
    pub value: ::core::option::Option<link_equal_operator::Value>,
}
/// Nested message and enum types in `LinkEqualOperator`.
pub mod link_equal_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        ReferLink(super::ReferLink),
        #[prost(message, tag = "2")]
        SpecialLink(super::SpecialLink),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkNotEqualOperator {
    #[prost(oneof = "link_not_equal_operator::Value", tags = "1, 2")]
    pub value: ::core::option::Option<link_not_equal_operator::Value>,
}
/// Nested message and enum types in `LinkNotEqualOperator`.
pub mod link_not_equal_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        ReferLink(super::ReferLink),
        #[prost(message, tag = "2")]
        SpecialLink(super::SpecialLink),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkInOperator {
    #[prost(oneof = "link_in_operator::Value", tags = "1, 2")]
    pub value: ::core::option::Option<link_in_operator::Value>,
}
/// Nested message and enum types in `LinkInOperator`.
pub mod link_in_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        ReferLink(super::ReferLink),
        #[prost(message, tag = "2")]
        SpecialLink(super::SpecialLink),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkNotInOperator {
    #[prost(oneof = "link_not_in_operator::Value", tags = "1, 2")]
    pub value: ::core::option::Option<link_not_in_operator::Value>,
}
/// Nested message and enum types in `LinkNotInOperator`.
pub mod link_not_in_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        ReferLink(super::ReferLink),
        #[prost(message, tag = "2")]
        SpecialLink(super::SpecialLink),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkIsNullOperator {}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkIsNotNullOperator {}
/// 引用链接
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReferLink {
    #[prost(oneof = "refer_link::ReferOnType", tags = "1, 2, 3, 4")]
    pub refer_on_type: ::core::option::Option<refer_link::ReferOnType>,
}
/// Nested message and enum types in `ReferLink`.
pub mod refer_link {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ReferOnType {
        #[prost(message, tag = "1")]
        ReferOnCurrentCard(super::ReferOnCurrentCard),
        #[prost(message, tag = "2")]
        ReferOnParameterCard(super::ReferOnParameterCard),
        #[prost(message, tag = "3")]
        ReferOnMember(super::ReferOnMember),
        #[prost(message, tag = "4")]
        ReferOnContextualCard(super::ReferOnContextualCard),
    }
}
/// 引用自当前卡片
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReferOnCurrentCard {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
}
/// 引用自参数卡片
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReferOnParameterCard {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
    #[prost(string, tag = "2")]
    pub parameter_card_type_id: ::prost::alloc::string::String,
}
/// 引用自当前成员
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReferOnMember {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
}
/// 引用自上下文卡片
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReferOnContextualCard {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
    /// 卡片ID，作为唯一标识符
    #[prost(uint64, tag = "2")]
    pub contextual_card_id: u64,
}
/// 具体的关联卡片值
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpecialLink {
    /// 卡片ID列表
    #[prost(uint64, repeated, tag = "1")]
    pub card_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(bool, tag = "2")]
    pub contains_discard: bool,
}
/// 引用自相对卡片
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReferOnRelativeCard {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
}
/// ==============================================================================
/// 链接属性条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkSubject {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
    #[prost(string, tag = "2")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkConditionItem {
    #[prost(message, optional, tag = "1")]
    pub subject: ::core::option::Option<WebLinkSubject>,
    #[prost(message, optional, tag = "2")]
    pub operator: ::core::option::Option<WebLinkOperator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkOperator {
    #[prost(oneof = "web_link_operator::OperatorType", tags = "1, 2, 3, 4, 5")]
    pub operator_type: ::core::option::Option<web_link_operator::OperatorType>,
}
/// Nested message and enum types in `WebLinkOperator`.
pub mod web_link_operator {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OperatorType {
        #[prost(message, tag = "1")]
        Equal(super::WebLinkEqualOperator),
        #[prost(message, tag = "2")]
        Contains(super::WebLinkContainsOperator),
        #[prost(message, tag = "3")]
        NotContains(super::WebLinkNotContainsOperator),
        #[prost(message, tag = "4")]
        IsNull(super::WebLinkIsNullOperator),
        #[prost(message, tag = "5")]
        IsNotNull(super::WebLinkIsNotNullOperator),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkEqualOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkContainsOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkNotContainsOperator {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkIsNullOperator {}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebLinkIsNotNullOperator {}
/// ==============================================================================
/// 关键词条件
/// ==============================================================================
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeywordConditionItem {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// 逻辑运算符
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogicOperator {
    And = 0,
    Or = 1,
}
impl LogicOperator {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            LogicOperator::And => "AND",
            LogicOperator::Or => "OR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AND" => Some(Self::And),
            "OR" => Some(Self::Or),
            _ => None,
        }
    }
}
/// 查询上下文
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryContext {
    #[prost(string, optional, tag = "1")]
    pub org_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub member_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "3")]
    pub parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 一致性读
    #[prost(bool, tag = "4")]
    pub consistent_read: bool,
}
/// 查询范围
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryScope {
    #[prost(string, repeated, tag = "1")]
    pub card_type_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 卡片ID列表，使用u64类型
    #[prost(uint64, repeated, tag = "2")]
    pub card_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, repeated, tag = "3")]
    pub container_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration = "super::common::CardState", repeated, tag = "4")]
    pub states: ::prost::alloc::vec::Vec<i32>,
}
/// 返回字段定义  默认包含所有内置属性，这里只需要指定自定义属性、是否包含卡片描述
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct YieldedField {
    #[prost(string, repeated, tag = "1")]
    pub custom_fields: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 表示返回所有内置属性
    #[prost(bool, tag = "2")]
    pub contains_all_custom_field: bool,
    /// 是否包含卡片描述，只有在打开卡片详情页时才需要
    #[prost(bool, tag = "3")]
    pub contains_desc: bool,
}
/// 返回关联卡定义
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct YieldedLink {
    #[prost(message, optional, tag = "1")]
    pub path_node: ::core::option::Option<super::common::PathNode>,
    #[prost(message, optional, tag = "2")]
    pub yielded_field: ::core::option::Option<YieldedField>,
    /// 关联衍生属性
    #[prost(map = "string, string", tag = "3")]
    pub fields_on_link: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bool, tag = "4")]
    pub contains_discard: bool,
    #[prost(message, repeated, tag = "5")]
    pub next_yielded_link: ::prost::alloc::vec::Vec<YieldedLink>,
}
/// 返回定义
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Yield {
    #[prost(message, optional, tag = "1")]
    pub yielded_field: ::core::option::Option<YieldedField>,
    #[prost(message, repeated, tag = "2")]
    pub yielded_links: ::prost::alloc::vec::Vec<YieldedLink>,
}
/// 排序和分页
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortAndPage {
    #[prost(message, optional, tag = "1")]
    pub page: ::core::option::Option<Page>,
    /// 支持多字段组合排序
    #[prost(message, repeated, tag = "2")]
    pub sorts: ::prost::alloc::vec::Vec<Sort>,
}
/// 分页信息
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Page {
    /// 第一页从0开始，如果小于0，表示不分页
    #[prost(uint32, tag = "1")]
    pub page_num: u32,
    /// 页大小
    #[prost(uint32, tag = "2")]
    pub page_size: u32,
}
/// 排序项
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sort {
    #[prost(message, optional, tag = "1")]
    pub sort_field: ::core::option::Option<SortField>,
    #[prost(enumeration = "super::common::SortWay", tag = "2")]
    pub sort_way: i32,
}
/// 排序字段
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortField {
    /// 支持使用多级关联节点的属性进行排序
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<super::common::Path>,
    /// 支持日期属性排序（包括内置日期属性，如创建日期，和自定义日期属性）
    /// 支持数字属性排序
    /// 支持文本属性排序
    /// 支持枚举属性排序，要提供枚举项的order信息，按照每一个枚举项对应的order来排序
    /// 支持关联属性排序，按照关联卡的标题来排序
    /// 支持一些内置属性的排序：
    ///      卡片类型、容器，这些就按照他们排序就行
    ///      标题：要按照拼接标题来排序
    ///      卡片编号：如果有custom_code，则按照custom_code排序，否则按照code_in_org进行排序，前者是文本，后置是数字
    /// 不支持计算属性排序、价值流状态排序、架构属性排序
    #[prost(oneof = "sort_field::FieldType", tags = "2, 3, 4, 5, 6, 7, 8")]
    pub field_type: ::core::option::Option<sort_field::FieldType>,
}
/// Nested message and enum types in `SortField`.
pub mod sort_field {
    /// 支持日期属性排序（包括内置日期属性，如创建日期，和自定义日期属性）
    /// 支持数字属性排序
    /// 支持文本属性排序
    /// 支持枚举属性排序，要提供枚举项的order信息，按照每一个枚举项对应的order来排序
    /// 支持关联属性排序，按照关联卡的标题来排序
    /// 支持一些内置属性的排序：
    ///      卡片类型、容器，这些就按照他们排序就行
    ///      标题：要按照拼接标题来排序
    ///      卡片编号：如果有custom_code，则按照custom_code排序，否则按照code_in_org进行排序，前者是文本，后置是数字
    /// 不支持计算属性排序、价值流状态排序、架构属性排序
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum FieldType {
        #[prost(message, tag = "2")]
        DateField(super::SortDateField),
        #[prost(message, tag = "3")]
        NumberField(super::SortNumberField),
        #[prost(message, tag = "4")]
        TextField(super::SortTextField),
        #[prost(message, tag = "5")]
        EnumField(super::SortEnumField),
        #[prost(message, tag = "6")]
        LinkField(super::SortLinkField),
        #[prost(message, tag = "7")]
        InnerField(super::SortInnerField),
        #[prost(message, tag = "8")]
        BlockState(super::SortBlockState),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortDateField {
    #[prost(string, tag = "1")]
    pub field_id: ::prost::alloc::string::String,
}
/// 内置属性：标题、编号、卡片类型、创建时间、更新时间、创建人、更新人、丢弃时间、归档时间
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortInnerField {
    #[prost(string, tag = "1")]
    pub field_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortTextField {
    #[prost(string, tag = "1")]
    pub field_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortNumberField {
    #[prost(string, tag = "1")]
    pub field_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortEnumField {
    #[prost(string, tag = "1")]
    pub field_id: ::prost::alloc::string::String,
    #[prost(map = "string, uint32", tag = "2")]
    pub enum_item_order_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u32,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortLinkField {
    #[prost(string, tag = "1")]
    pub lt_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::common::LinkPosition", tag = "2")]
    pub position: i32,
}
/// 阻塞状态
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SortBlockState {
    #[prost(string, tag = "1")]
    pub block_lt_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::common::LinkPosition", tag = "2")]
    pub position: i32,
}
/// 卡片查询请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardQueryRequest {
    #[prost(message, optional, tag = "1")]
    pub query_context: ::core::option::Option<QueryContext>,
    #[prost(message, optional, tag = "2")]
    pub query_scope: ::core::option::Option<QueryScope>,
    #[prost(message, optional, tag = "3")]
    pub condition: ::core::option::Option<Condition>,
    #[prost(message, optional, tag = "4")]
    pub r#yield: ::core::option::Option<Yield>,
    #[prost(message, optional, tag = "6")]
    pub sort_and_page: ::core::option::Option<SortAndPage>,
}
/// 卡片查询请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardQueryResponse {
    #[prost(message, repeated, tag = "1")]
    pub cards: ::prost::alloc::vec::Vec<super::model::Card>,
    /// 返回的数量，分页后不等于总数
    #[prost(uint32, tag = "2")]
    pub count: u32,
    /// 总数
    #[prost(uint32, tag = "3")]
    pub total: u32,
}
/// 卡片计数请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardCountRequest {
    #[prost(message, optional, tag = "1")]
    pub query_context: ::core::option::Option<QueryContext>,
    #[prost(message, optional, tag = "2")]
    pub query_scope: ::core::option::Option<QueryScope>,
    #[prost(message, optional, tag = "3")]
    pub condition: ::core::option::Option<Condition>,
}
/// 卡片计数响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardCountResponse {
    /// 卡片计数结果
    #[prost(uint32, tag = "1")]
    pub count: u32,
}
/// 卡片ID查询请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardIdQueryRequest {
    #[prost(message, optional, tag = "1")]
    pub query_context: ::core::option::Option<QueryContext>,
    #[prost(message, optional, tag = "2")]
    pub query_scope: ::core::option::Option<QueryScope>,
    #[prost(message, optional, tag = "3")]
    pub condition: ::core::option::Option<Condition>,
}
/// 查询ID响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIdsResponse {
    /// 卡片ID列表，使用u64类型
    #[prost(uint64, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<u64>,
}
/// 按分组计数请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardCountByGroupRequest {
    #[prost(message, optional, tag = "1")]
    pub query_context: ::core::option::Option<QueryContext>,
    #[prost(message, optional, tag = "2")]
    pub query_scope: ::core::option::Option<QueryScope>,
    #[prost(message, optional, tag = "3")]
    pub condition: ::core::option::Option<Condition>,
    #[prost(message, optional, tag = "4")]
    pub group_by: ::core::option::Option<super::linkquery::LtWithPosition>,
    #[prost(string, repeated, tag = "5")]
    pub group_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 按分组计数响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardCountByGroupResponse {
    /// 每个组ID对应的卡片数量
    #[prost(map = "string, uint32", tag = "1")]
    pub counts: ::std::collections::HashMap<::prost::alloc::string::String, u32>,
}
/// 查询卡片标题请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryCardTitlesRequest {
    /// 卡片ID列表
    #[prost(string, repeated, tag = "1")]
    pub card_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 查询卡片标题响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryCardTitlesResponse {
    /// 卡片ID到标题的映射
    #[prost(map = "string, message", tag = "1")]
    pub titles: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::model::Title,
    >,
}
