// This file is @generated by prost-build.
/// 卡片状态
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CardState {
    /// 进行中
    Active = 0,
    /// 已丢弃
    Discarded = 1,
    /// 已归档
    Archived = 2,
}
impl CardState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CardState::Active => "Active",
            CardState::Discarded => "Discarded",
            CardState::Archived => "Archived",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Active" => Some(Self::Active),
            "Discarded" => Some(Self::Discarded),
            "Archived" => Some(Self::Archived),
            _ => None,
        }
    }
}
/// 拼接标题区域枚举，表示前缀还是后缀
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TitleJointArea {
    /// 前缀
    Prefix = 0,
    /// 后缀
    Suffix = 1,
}
impl TitleJointArea {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TitleJointArea::Prefix => "Prefix",
            TitleJointArea::Suffix => "Suffix",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Prefix" => Some(Self::Prefix),
            "Suffix" => Some(Self::Suffix),
            _ => None,
        }
    }
}
/// 连接方向枚举
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LinkPosition {
    /// 源侧
    Src = 0,
    /// 目标侧
    Dest = 1,
}
impl LinkPosition {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            LinkPosition::Src => "Src",
            LinkPosition::Dest => "Dest",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Src" => Some(Self::Src),
            "Dest" => Some(Self::Dest),
            _ => None,
        }
    }
}
/// 排序方式
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SortWay {
    Asc = 0,
    Desc = 1,
    Unsorted = 2,
}
impl SortWay {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SortWay::Asc => "Asc",
            SortWay::Desc => "Desc",
            SortWay::Unsorted => "Unsorted",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Asc" => Some(Self::Asc),
            "Desc" => Some(Self::Desc),
            "Unsorted" => Some(Self::Unsorted),
            _ => None,
        }
    }
}
/// 路径相关定义，用来表示节点之间的多级关联关系
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Path {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<PathNode>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PathNode {
    /// 关联关系类型ID
    #[prost(string, tag = "1")]
    pub lt_id: ::prost::alloc::string::String,
    /// 关联方向
    #[prost(string, tag = "2")]
    pub position: ::prost::alloc::string::String,
}
