// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(
        oneof = "request::RequestType",
        tags = "4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22"
    )]
    pub request_type: ::core::option::Option<request::RequestType>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum RequestType {
        #[prost(message, tag = "4")]
        Auth(super::super::auth::AuthRequest),
        #[prost(message, tag = "5")]
        CardQuery(super::super::query::CardQueryRequest),
        #[prost(message, tag = "6")]
        CardCount(super::super::query::CardCountRequest),
        #[prost(message, tag = "7")]
        CardIdQuery(super::super::query::CardIdQueryRequest),
        #[prost(message, tag = "8")]
        LinkQuery(super::super::linkquery::LinkQueryRequest),
        #[prost(message, tag = "9")]
        LinkFetch(super::super::linkquery::LinkFetchRequest),
        #[prost(message, tag = "10")]
        BatchCreateCard(super::super::write::BatchCreateCardRequest),
        #[prost(message, tag = "11")]
        BatchCreateLink(super::super::write::BatchCreateLinkRequest),
        #[prost(message, tag = "12")]
        BatchUpdateCard(super::super::write::BatchUpdateCardRequest),
        #[prost(message, tag = "13")]
        BatchUpdateLink(super::super::write::BatchUpdateLinkRequest),
        #[prost(message, tag = "14")]
        BatchDeleteLink(super::super::write::BatchDeleteLinkRequest),
        #[prost(message, tag = "15")]
        BatchUpdateCardState(super::super::write::BatchUpdateCardStateRequest),
        #[prost(message, tag = "16")]
        BatchUpdateCardValueStreamStatus(
            super::super::write::BatchUpdateCardValueStreamStatusRequest,
        ),
        #[prost(message, tag = "17")]
        BatchUpdateCardTitle(super::super::write::BatchUpdateCardTitleRequest),
        #[prost(message, tag = "18")]
        BatchUpdateCardFields(super::super::write::BatchUpdateCardFieldRequest),
        #[prost(message, tag = "19")]
        UpdateLogLevel(super::super::admin::UpdateLogLevelRequest),
        #[prost(message, tag = "20")]
        CardCountByGroup(super::super::query::CardCountByGroupRequest),
        #[prost(message, tag = "21")]
        DatabaseStats(super::super::admin::DatabaseStatsRequest),
        #[prost(message, tag = "22")]
        QueryCardTitles(super::super::query::QueryCardTitlesRequest),
    }
}
