// This file is @generated by prost-build.
/// 更新日志级别请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateLogLevelRequest {
    /// 新的日志级别配置
    #[prost(string, tag = "1")]
    pub log_level: ::prost::alloc::string::String,
}
/// 更新日志级别响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateLogLevelResponse {
    /// 操作是否成功
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 新的日志级别
    #[prost(string, tag = "2")]
    pub log_level: ::prost::alloc::string::String,
    /// 详细信息
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// 数据库统计请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DatabaseStatsRequest {
    /// 是否包含详细的缓存统计信息
    #[prost(bool, optional, tag = "1")]
    pub include_cache_details: ::core::option::Option<bool>,
}
/// 数据库统计响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DatabaseStatsResponse {
    /// 基础统计信息
    ///
    /// 节点总数
    #[prost(uint64, tag = "1")]
    pub total_vertices: u64,
    /// 边总数（去重）
    #[prost(uint64, tag = "2")]
    pub total_edges: u64,
    /// 节点类型数
    #[prost(uint32, tag = "3")]
    pub vertex_type_size: u32,
    /// 边类型数
    #[prost(uint32, tag = "4")]
    pub edge_type_size: u32,
    /// 缓存统计信息
    #[prost(message, optional, tag = "5")]
    pub cache_stats: ::core::option::Option<CacheStats>,
    /// RocksDB统计信息
    ///
    /// RocksDB内部统计信息
    #[prost(string, optional, tag = "7")]
    pub rocksdb_stats: ::core::option::Option<::prost::alloc::string::String>,
}
/// 缓存统计信息
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CacheStats {
    /// 节点LRU缓存数量
    #[prost(uint64, tag = "1")]
    pub vertex_lru_cache_size: u64,
    /// 节点描述LRU缓存数量
    #[prost(uint64, tag = "2")]
    pub desc_lru_cache_size: u64,
}
