plugin.id=builtin
plugin.class=cn.planka.notification.plugin.builtin.BuiltinPluginDef
plugin.version=1.0.0
plugin.provider=Planka
plugin.dependencies=
plugin.requires=*
plugin.description=系统内置站内信通知渠道
