// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchCreateCardRequest {
    #[prost(message, repeated, tag = "1")]
    pub cards: ::prost::alloc::vec::Vec<super::model::Card>,
}
/// 批量更新卡片请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchUpdateCardRequest {
    #[prost(message, repeated, tag = "1")]
    pub cards: ::prost::alloc::vec::Vec<super::model::Card>,
}
/// 批量部分更新卡片请求
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchUpdateCardFieldRequest {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<UpdateCardFieldRequest>,
}
/// 卡片价值流状态
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValueStreamStatus {
    #[prost(string, tag = "1")]
    pub stream_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub status_id: ::prost::alloc::string::String,
}
/// 支持更新卡片的指定属性
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateCardFieldRequest {
    /// 卡片ID，使用u64类型
    #[prost(uint64, tag = "1")]
    pub card_id: u64,
    #[prost(message, optional, tag = "2")]
    pub title: ::core::option::Option<super::model::Title>,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "super::common::CardState", optional, tag = "4")]
    pub state: ::core::option::Option<i32>,
    /// 价值流状态作为一个整体
    #[prost(message, optional, tag = "5")]
    pub value_stream_status: ::core::option::Option<ValueStreamStatus>,
    /// 更多可选的更新属性
    #[prost(string, optional, tag = "6")]
    pub custom_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub container_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "8")]
    pub position: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "9")]
    pub discarded_at: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "10")]
    pub archived_at: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "11")]
    pub updated_at: ::core::option::Option<i64>,
    #[prost(string, optional, tag = "12")]
    pub discard_reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub restore_reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "14")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 自定义属性值，如果map中含有某个字段，则更新该字段，否则保持原值
    #[prost(map = "string, message", tag = "15")]
    pub custom_field_value_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::field::FieldValue,
    >,
}
/// 批量更新卡片标题
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchUpdateCardTitleRequest {
    #[prost(message, repeated, tag = "1")]
    pub requests: ::prost::alloc::vec::Vec<UpdateCardTitleRequest>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateCardTitleRequest {
    /// 卡片ID，使用u64类型
    #[prost(uint64, tag = "1")]
    pub card_id: u64,
    #[prost(message, optional, tag = "2")]
    pub title: ::core::option::Option<super::model::Title>,
}
/// 更新卡片周期状态
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchUpdateCardStateRequest {
    /// 卡片ID列表
    #[prost(uint64, repeated, tag = "1")]
    pub card_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(enumeration = "super::common::CardState", tag = "2")]
    pub state: i32,
}
/// 更新卡片价值流状态
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchUpdateCardValueStreamStatusRequest {
    /// 卡片ID列表
    #[prost(uint64, repeated, tag = "1")]
    pub card_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, tag = "2")]
    pub stream_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub status_id: ::prost::alloc::string::String,
}
/// 批量操作卡片通用的返回结构
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchCardCommonResponse {
    /// 成功数量
    #[prost(int32, tag = "1")]
    pub success: i32,
    /// 更新失败的卡片id
    ///
    /// 卡片ID列表
    #[prost(uint64, repeated, tag = "2")]
    pub failed_ids: ::prost::alloc::vec::Vec<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchCreateLinkRequest {
    #[prost(message, repeated, tag = "1")]
    pub links: ::prost::alloc::vec::Vec<super::model::Link>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchUpdateLinkRequest {
    #[prost(message, repeated, tag = "1")]
    pub links: ::prost::alloc::vec::Vec<super::model::Link>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchLinkCommonResponse {
    /// 成功数量
    #[prost(int32, tag = "1")]
    pub success: i32,
    /// 更新失败的关联关系
    #[prost(message, repeated, tag = "2")]
    pub failed_links: ::prost::alloc::vec::Vec<super::model::Link>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchDeleteLinkRequest {
    #[prost(message, repeated, tag = "1")]
    pub links: ::prost::alloc::vec::Vec<super::model::Link>,
}
