// This file is @generated by prost-build.
/// 从给定的卡片id出发，沿着给定的关联关系+方向，查询关联关系
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkQueryRequest {
    /// card_id 现在是 u64 类型
    #[prost(uint64, repeated, tag = "1")]
    pub card_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(message, repeated, tag = "2")]
    pub lt_with_position: ::prost::alloc::vec::Vec<LtWithPosition>,
}
/// 根据 srcId + ltId + destId 三元组查找关系，这个三元组可以一条唯一的关系
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkFetchRequest {
    #[prost(message, repeated, tag = "1")]
    pub link_keys: ::prost::alloc::vec::Vec<super::model::LinkKey>,
}
/// 查询关联关系响应
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkQueryResponse {
    #[prost(message, repeated, tag = "1")]
    pub links: ::prost::alloc::vec::Vec<super::model::Link>,
}
/// 关联关系+方向
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LtWithPosition {
    #[prost(string, tag = "1")]
    pub lt_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::common::LinkPosition", tag = "2")]
    pub position: i32,
}
