// This file is @generated by prost-build.
/// 卡片
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Card {
    /// ==================== 标识信息 ====================
    ///
    /// 卡片ID，使用u64类型
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub code_in_org: i64,
    #[prost(string, tag = "4")]
    pub custom_code: ::prost::alloc::string::String,
    /// 卡片类型ID
    #[prost(string, tag = "5")]
    pub type_id: ::prost::alloc::string::String,
    /// ==================== 基本信息 ====================
    #[prost(message, optional, tag = "6")]
    pub title: ::core::option::Option<Title>,
    #[prost(string, tag = "7")]
    pub description: ::prost::alloc::string::String,
    /// ==================== 状态信息 ====================
    ///
    /// 卡片周期状态
    #[prost(enumeration = "super::common::CardState", tag = "8")]
    pub state: i32,
    /// 价值流定义ID
    #[prost(string, tag = "9")]
    pub stream_id: ::prost::alloc::string::String,
    /// 价值流状态ID  无需记录价值流阶段ID
    #[prost(string, tag = "10")]
    pub status_id: ::prost::alloc::string::String,
    /// ==================== 属性值 ====================
    #[prost(map = "string, message", tag = "11")]
    pub custom_field_value_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::field::FieldValue,
    >,
    /// ==================== 关联卡片 ====================
    #[prost(map = "string, message", tag = "12")]
    pub link_card_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        CardList,
    >,
    /// ==================== 审计信息 ====================
    #[prost(int64, tag = "13")]
    pub created_at: i64,
    #[prost(int64, tag = "14")]
    pub updated_at: i64,
    /// 丢弃时间
    #[prost(int64, tag = "15")]
    pub discarded_at: i64,
    /// 归档时间
    #[prost(int64, tag = "16")]
    pub archived_at: i64,
}
/// 标题
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Title {
    #[prost(oneof = "title::TitleType", tags = "1, 2")]
    pub title_type: ::core::option::Option<title::TitleType>,
}
/// Nested message and enum types in `Title`.
pub mod title {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum TitleType {
        #[prost(message, tag = "1")]
        Pure(super::PureTitle),
        #[prost(message, tag = "2")]
        Joint(super::JointTitle),
    }
}
/// 纯标题
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PureTitle {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
/// 拼接标题
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JointTitle {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "TitleJointArea", tag = "2")]
    pub area: i32,
    #[prost(message, repeated, tag = "3")]
    pub multi_parts: ::prost::alloc::vec::Vec<JointTitleParts>,
}
/// 拼接标题的组成部分-多项
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JointTitleParts {
    #[prost(message, repeated, tag = "1")]
    pub parts: ::prost::alloc::vec::Vec<JointTitlePart>,
}
/// 拼接标题的组成部分-单项
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JointTitlePart {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
/// 卡片列表
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CardList {
    #[prost(message, repeated, tag = "1")]
    pub cards: ::prost::alloc::vec::Vec<Card>,
}
/// 拼接区域枚举
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TitleJointArea {
    /// 前缀
    Prefix = 0,
    /// 后缀
    Suffix = 1,
}
impl TitleJointArea {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TitleJointArea::Prefix => "PREFIX",
            TitleJointArea::Suffix => "SUFFIX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PREFIX" => Some(Self::Prefix),
            "SUFFIX" => Some(Self::Suffix),
            _ => None,
        }
    }
}
/// 卡片间的关联关系
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Link {
    /// 关联ID，使用u64类型
    #[prost(uint64, tag = "1")]
    pub id: u64,
    /// 关联关系定义id
    #[prost(string, tag = "2")]
    pub lt_id: ::prost::alloc::string::String,
    /// 源节点卡片id
    #[prost(uint64, tag = "3")]
    pub src_id: u64,
    /// 目标节点卡片id
    #[prost(uint64, tag = "4")]
    pub dest_id: u64,
    /// 关联关系上的属性：衍生属性
    #[prost(message, repeated, tag = "5")]
    pub field_values: ::prost::alloc::vec::Vec<super::field::FieldValueOnLink>,
}
/// 卡片间的关联关系单元
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkKey {
    /// 关联关系定义id
    #[prost(string, tag = "2")]
    pub lt_id: ::prost::alloc::string::String,
    /// 源节点卡片id
    #[prost(uint64, tag = "3")]
    pub src_id: u64,
    /// 目标节点卡片id
    #[prost(uint64, tag = "4")]
    pub dest_id: u64,
}
